name: Build and deploy Lockkeeper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lockkeeper-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        shell: bash
        run: |
          npm install

      - name: Build
        shell: bash
        run: |
          npm run build --if-present

      - name: Test
        shell: bash
        run: |
          npm run test --if-present

      - name: Deploy
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: "Backface"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
